language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

before_install:
  - composer self:update

before_script:
  - cd taskmanager/
  - travis_retry composer install
script:
  - ./vendor/bin/phpspec run
  - ./vendor/bin/behat

matrix:
  allow_failures:
    - php: 7.3
    - php: nightly

notifications:
  email: false